- hosts: all
  become: yes
  roles:
  - role: local-persistent-volumes

- import_playbook: ./kubespray/cluster.yml

- hosts: kube1
  become: yes
  roles:
  - role: helm
  - { role: k8s-namespace, k8s_namespace: "percona" }
  - { role: k8s-percona-xtradb-cluster, k8s_namespace: "percona", percona_xtradb_helm_release: "percona", percona_xtradb_root_password: "p@ssw0rd" }
